"""
Django settings for online_class project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bpuuomtkk^_)1b#)@1bjtwk5fd0f74z1l8#sbwey92$ujar#u*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'class_app',
    # 'paystack',
    # 'django_admin_logs',
    'django.contrib.admin',
    'django.contrib.auth',
    # 'login_history',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'captcha',
    'apis',
    'rest_framework',


   



]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'online_class.middleware.AdminActivityMiddleware',

]

ROOT_URLCONF = 'online_class.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'online_class.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    
    
        'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'new_class',
        'USER': 'postgres',
        'PASSWORD': 'ojugbele2006',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



LOGIN_REDIRECT_URL = 'user_profile'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

import os

STATIC_URL = '/static/'
# STATICFILES_DIRS  =  os.path.join(BASE_DIR, 'class/static'),
STATIC_ROOT = BASE_DIR / 'class/static'


# STATIC_ROOT = '/home/elearni3/e-learningclass.com.ng/static'




MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# MEDIA_ROOT = '/home/elearni3/e-learningclass.com.ng/media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # e.g., 'smtp.gmail.com' for Gmail
EMAIL_PORT = 587  # e.g., 587 for TLS, 465 for SSL
EMAIL_USE_TLS = True  # Set to False if you use SSL
EMAIL_USE_SSL = False  # Set to True if you use SSL
EMAIL_HOST_USER = 'ojugbelelateef2006@gmail.com'
EMAIL_HOST_PASSWORD = 'yshhvvigaryqlabg'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


DJANGO_ADMIN_LOGS_DELETABLE = True
DJANGO_ADMIN_LOGS_ENABLED = True



STRIPE_PUBLIC_KEY = 'pk_test_51NaNqwCQFS1AwSw0ARXtsHymmWmivsF1pekt4fRgGAd4WvzB860QbGR59B9MLGcbYThjSlZThhBnPb9XxAPuwksj00gFCTINiD'
STRIPE_SECRET_KEY = 'sk_test_51NaNqwCQFS1AwSw0hUmtPmGkbAFk2GAvmWoSIod0vq0FfVI5W4alYQmP51tYME7gjFFhez8W3ZpF8D0HtTzwT5MU00TRbiCzwz'


# STRIPE_WEBHOOK_SECRET = 'your_webhook_secret'
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

PAYSTACK_PUBLIC_KEY = 'pk_test_f9d4e9c4b70a553a45fd67aea9e4f1429de302cf'
PAYSTACK_SECRET_KEY = 'sk_test_2de22e65cd85be13d98741474297a8e5bf84dcf5'


FLUTTERWAVE_PUBLIC_KEY = 'FLWPUBK_TEST-00fb23c54507e772ce6117eadb808f8e-X'
FLUTTERWAVE_SECRET_KEY = 'FLWSECK_TEST-accb5e1b97a1114fdb1b7de86d2fa47e-X'


handler404 = 'online_class.views.custom_404'
handler500 = 'online_class.views.custom_500'

